
Feature('Test the database API');

const assert = require('assert');
const axios = require('axios');
const { rmSync } = require('fs');


Scenario('Should post a question', async (I) => {
  const card = require('./card.json');
  // Set the endpoint URL
  const url = 'http://localhost:3000/api/card';

  // Set the request headers
  const headers = {
    'Content-Type': 'application/json',
    'X-Metabase-Session': 'dc601433-1d27-4d59-93c2-2961016a6d10',
  };

  const response = await axios.post(url, card, { headers });
  assert.strictEqual(response.data.name, 'Test Question Generated By API POST Call');

}).tag('@card');
